version: '3'

services:
  disclost-service:
    image: disclost:latest
    build:
      context: .
    entrypoint: ["poetry", "run", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
