version: '3'

services:
  disclost-service:
    image: disclost:latest
    depends_on:
      - database
    build:
      context: .
    entrypoint: ["poetry", "run", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0"]
    environment:
      DB_CONN_STR: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
